title: Honor Play Volte
description: Get Volte on Honor Play with root
theme: just-the-docs
color_scheme: light

url: https://just-the-docs.github.io
exclude: 
  - .scripts/
  - .gems/

aux_links:
  Github: https://github.com/williamyang98/honor_play_root_volte_fix
