title: Honor Play Volte
description: Get Volte on Honor Play with root
theme: just-the-docs
color_scheme: light

url: https://just-the-docs.github.io
exclude: 
  - .scripts/
  - .gems/

nav_external_links:
  - title: Github
    url: https://github.com/williamyang98/honor_play_root_volte_fix
  - title: XDA discussion
    url: https://xdaforums.com/t/honor-play-volte-fix-with-paid-bootloader-unlock.4687230
